FROM python

WORKDIR /app

COPY . .

RUN pip3 install -r requirement.txt

EXPOSE 5000

ARG GEMINI_API_KEY=""
ARG OPENAI_API_KEY=""
ARG CLAUDE_API_KEY=""

ENV GEMINI_API_KEY=${GEMINI_API_KEY} 
ENV OPENAI_API_KEY=${OPENAI_API_KEY} 
ENV CLAUDE_API_KEY=${CLAUDE_API_KEY} 

CMD ["python3", "app.py"]