name: Flask Test Build Workflow
on:
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip3 install -r requirement.txt

      - name: Run tests
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          python -m unit_test.test_index
          python -m unit_test.test_gpt
          python -m unit_test.test_claude
          python -m unit_test.test_gemini

  build-docker-image:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build \
          -t dohanyan/threeai:latest \
          --build-arg GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
          --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          --build-arg CLAUDE_API_KEY=${{ secrets.CLAUDE_API_KEY }} \
          .

      - name: Save Docker image as tar
        run: docker save dohanyan/threeai:latest -o image.tar
      
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: image.tar
  
  push-to-dockerhub:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      
      - name: Load image from tar and push
        run: |
          docker load -i image.tar
          docker push dohanyan/threeai:latest